name: .NET CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore UniversityGrades.csproj

      - name: Build
        run: dotnet build UniversityGrades.csproj --no-restore

      - name: Test
        run: |
          if find . -name "*Tests.csproj" | grep -q .; then
            dotnet test --no-build --verbosity normal
          else
            echo "No se encontró proyecto de pruebas"
          fi
