name: .NET CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore test1.sln

      - name: Build
        run: dotnet build test1.sln --no-restore

      - name: Test
        run: dotnet test test1.sln --no-build --verbosity normal || echo "No tests"
